# Generated by Django 3.1.7 on 2021-03-23 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=30)),
                ('telephone', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_data', models.DateTimeField(blank=True)),
                ('cost', models.CharField(blank=True, default='', max_length=100)),
                ('profit', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
